In [7]:
import pandas as pd

tabla = pd.read_csv('/content/students.csv')
tabla

,Id,User,Unnamed: 2,Pass,Paternal,Maternal,Name,Email,Faculty,Unnamed: 9
0,1,12136038,1,70048933,ABAD,HUACHIN,CARLOS DARWIN,-,ECOTURISMO,NaN
1,2,24137004,1,76652472,ACUÑA,SAL Y ROSAS,ALEXANDER JONATHAN,24137004@unamad.edu.pe,ECOTURISMO,NaN
2,3,21132022,1,79787815,ACURIO,ROBLES,JOEL,jacurior21-1ec@unamad.edu.pe,ECOTURISMO,NaN
3,4,21236022,1,76256614,ACOSTA,GONZALES,NAYDELINE HAJALE,8040403@unamad.edu.pe,ECOTURISMO,NaN
4,5,19137031,1,71470013,ACOSTA,YNUMA,DIEGO LEANDRO,dacostay21-2cf@unamad.edu.pe,ECOTURISMO,NaN
...,...,...,...,...,...,...,...,...,...,...
2403,2404,18136002,1,41930879,PEÑA,GOMEZ,PAOLA GRACIELA,paolapg@unamad.edu.pe,ECOTURISMO,NaN
2404,2405,17136009,1,62483866,PEÑA,GUDIEL,ALBERTO BRANDON,abgudiel@unamad.edu.pe,ECOTURISMO,NaN
2405,2406,22237004,1,61657879,PEDRAZA,PALOMINO,MIGUEL,22237004@unamad.edu.pe,ECOTURISMO,NaN
2406,2407,20237007,1,76810538,PAZ,HUAMAN,CARLOS MANUEL,cpazh@unamad.edu.pe,ECOTURISMO,NaN
2407,2408,22132006,1,73248553,PAZ,FLORES,PEGGIE SELENA,ppaz22@unamad.edu.pe,ECOTURISMO,NaN

In [8]:
# Ver cabeceras de columnas
tabla.columns

Index(['Id', 'User', 'Unnamed: 2', 'Pass', 'Paternal', 'Maternal', 'Name',
       'Email', 'Faculty', 'Unnamed: 9'],
      dtype='object')

In [9]:
# ver estructura del dataframe
tabla.shape

(2408, 10)

In [12]:
# Visualizar solo las 5 filas
tabla.head()

,Id,User,Unnamed: 2,Pass,Paternal,Maternal,Name,Email,Faculty,Unnamed: 9
0,1,12136038,1,70048933,ABAD,HUACHIN,CARLOS DARWIN,-,ECOTURISMO,NaN
1,2,24137004,1,76652472,ACUÑA,SAL Y ROSAS,ALEXANDER JONATHAN,24137004@unamad.edu.pe,ECOTURISMO,NaN
2,3,21132022,1,79787815,ACURIO,ROBLES,JOEL,jacurior21-1ec@unamad.edu.pe,ECOTURISMO,NaN
3,4,21236022,1,76256614,ACOSTA,GONZALES,NAYDELINE HAJALE,8040403@unamad.edu.pe,ECOTURISMO,NaN
4,5,19137031,1,71470013,ACOSTA,YNUMA,DIEGO LEANDRO,dacostay21-2cf@unamad.edu.pe,ECOTURISMO,NaN

In [13]:
# Visualizar las ultimas 5 filas
tabla.tail()

,Id,User,Unnamed: 2,Pass,Paternal,Maternal,Name,Email,Faculty,Unnamed: 9
2403,2404,18136002,1,41930879,PEÑA,GOMEZ,PAOLA GRACIELA,paolapg@unamad.edu.pe,ECOTURISMO,NaN
2404,2405,17136009,1,62483866,PEÑA,GUDIEL,ALBERTO BRANDON,abgudiel@unamad.edu.pe,ECOTURISMO,NaN
2405,2406,22237004,1,61657879,PEDRAZA,PALOMINO,MIGUEL,22237004@unamad.edu.pe,ECOTURISMO,NaN
2406,2407,20237007,1,76810538,PAZ,HUAMAN,CARLOS MANUEL,cpazh@unamad.edu.pe,ECOTURISMO,NaN
2407,2408,22132006,1,73248553,PAZ,FLORES,PEGGIE SELENA,ppaz22@unamad.edu.pe,ECOTURISMO,NaN

In [14]:
# Ver los tipos de datos
tabla.dtypes

Id              int64
User            int64
Unnamed: 2      int64
Pass            int64
Paternal       object
Maternal       object
Name           object
Email          object
Faculty        object
Unnamed: 9    float64
dtype: object

In [15]:
# Que datos estan vacios
tabla.isnull()

,Id,User,Unnamed: 2,Pass,Paternal,Maternal,Name,Email,Faculty,Unnamed: 9
0,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
2403,False,False,False,False,False,False,False,False,False,True
2404,False,False,False,False,False,False,False,False,False,True
2405,False,False,False,False,False,False,False,False,False,True
2406,False,False,False,False,False,False,False,False,False,True
2407,False,False,False,False,False,False,False,False,False,True

In [16]:
# Cuantos datos son nulos
tabla.isnull().sum()

Id               0
User             0
Unnamed: 2       0
Pass             0
Paternal         0
Maternal         0
Name             0
Email           99
Faculty         51
Unnamed: 9    2408
dtype: int64

In [17]:
# Informacion de cada columna, cuantas datos no nulos tengo ?
tabla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2408 entries, 0 to 2407
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          2408 non-null   int64
 1   User        2408 non-null   int64
 2   Unnamed: 2  2408 non-null   int64
 3   Pass        2408 non-null   int64
 4   Paternal    2408 non-null   object
 5   Maternal    2408 non-null   object
 6   Name        2408 non-null   object
 7   Email       2309 non-null   object
 8   Faculty     2357 non-null   object
 9   Unnamed: 9  0 non-null      float64
dtypes: float64(1), int64(4), object(5)
memory usage: 188.2+ KB

En pandas se pueden realizar los siguientes tipos de calculos

* promedio
* suma
* valor minimo
* valor maximo
* mediana